export const refs = {
  mainMarkup: document.querySelector('.main-render'),
  form: document.querySelector('.search-form'),
  btn: document.querySelector('.submit-btn'),
  modal: document.querySelector('.modal'),
  backToTopBtn: document.querySelector('.back-to-top-btn'),
  pageProgressBar: document.querySelector('.progress-bar'),
  myLibBtn: document.querySelector('.library__btn'),
  // pagination
  pagination: document.querySelector('.pagination-main'),
  paginationSearch: document.querySelector('.pagination-search'),
  paginationWatched: document.querySelector('.pagination-watched'),
  paginationQueue: document.querySelector('.pagination-queue'),
  homeBtn: document.querySelector('.home__btn'),
  logoBtn: document.querySelector('.logo-link'),
  watchedBtn: document.querySelector('.watched'),
  queueBtn: document.querySelector('.queue'),
  input: document.querySelector('.input-form'),
  placeholder: document.querySelector('.input-form').placeholder,
  selectLang: document.querySelector('.select'),
  loginBtn: document.querySelector('.login__btn'),
  clockFrame: document.querySelector('.clock__frame'),
  // Login Modal
  loginBackdrop: document.querySelector('.modal-backdrop'),
  loginModal: document.querySelector('.modal-container'),
  openLoginBtn: document.querySelector('.nav-btn.login__btn'),
  closeLoginBtn: document.querySelector('button[data-action="close"]'),
  logoutBtn: document.querySelector('.nav-btn.logout__btn'),
  loginForm: document.querySelector('.modal-form.login'),
  registerForm: document.querySelector('.modal-form.register'),
  modalBtn: document.querySelectorAll(
    '.modal-form button[data-action="toggle"]'
  ),
  // Students Modal
  backdropStEl: document.querySelector('.backdrop--students'),
  listStudents: document.querySelector('.team-items'),
  linkToDev: document.getElementById('openModalLink'),
  closeModalBtn: document.getElementById('closeModalStBtn'),
  closeModalBtnX: document.getElementById('closeModalStBtnX'),
  renderModal: document.querySelector('.team-items'),
  studModalLink: document.querySelector('.footer-link'),
};
